FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=composer /usr/bin/composer /usr/bin/composer
COPY ./devops-test-api /var/www/devops-test-api

WORKDIR /var/www/devops-test-api

RUN apt-get update && apt-get install -y \
    software-properties-common && \
    add-apt-repository ppa:ondrej/php && \
    apt-get update && apt-get install -y \
    php8.2-common \
    php8.2-zip \
    php8.2-mbstring \
    php8.2-xml \
    php8.2-curl \
    php8.2-intl \
    php8.2-cli \
    unzip \
    git \
    curl

RUN composer install
RUN apt update && apt install -y php8.2-mysql

CMD [ "php", "artisan", "serve", "--host=0.0.0.0" ]